### ISSUE TITLE
ERROR: TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by wyssicky25** [JijaProGamer/Youtube-Rumble-View-Bot#34]
ERROR: TypeError: Cannot read properties of undefined (reading '0')
    at generateJob (file:///C:/Users/BerDauPhong/Documents/Bots/Youtube-Rumble-View-Bot/main/server/generate_jobs.js:82:25)
    at generateJobs (file:///C:/Users/BerDauPhong/Documents/Bots/Youtube-Rumble-View-Bot/main/server/generate_jobs.js:123:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/Users/BerDauPhong/Documents/Bots/Youtube-Rumble-View-Bot/main/server.js:156:33 Promise {
  <rejected> TypeError: Cannot read properties of undefined (reading '0')
      at generateJob (file:///C:/Users/BerDauPhong/Documents/Bots/Youtube-Rumble-View-Bot/main/server/generate_jobs.js:82:25)
      at generateJobs (file:///C:/Users/BerDauPhong/Documents/Bots/Youtube-Rumble-View-Bot/main/server/generate_jobs.js:123:9)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async file:///C:/Users/BerDauPhong/Documents/Bots/Youtube-Rumble-View-Bot/main/server.js:156:33
}

**Comment by JijaProGamer** [comment]
Can you provide any information about when and how this happened?

**Comment by JijaProGamer** [comment]
Fix is upcoming next week.

**Comment by JijaProGamer** [comment]
It's been fixed this version
