### ISSUE TITLE
App is stuck on a proxy checking

### ISSUE THREAD

**Issue by MBoberski** [JijaProGamer/Youtube-Rumble-View-Bot#35]
I downloaded latest code added a few proxy for testing and it is stuck on proxy check. I also get:

```
ERROR: ReferenceError: start is not defined
    at file:///C:/Users/marci/OneDrive/Pictures/Desktop/Youtube-Rumble-View-Bot-master/node_modules/fast-proxy-tester/index.js:240:47
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) Promise {
  <rejected> ReferenceError: start is not defined
      at file:///C:/Users/marci/OneDrive/Pictures/Desktop/Youtube-Rumble-View-Bot-master/node_modules/fast-proxy-tester/index.js:240:47
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
}
```

**Comment by JijaProGamer** [comment]
Fix is upcoming next week, till then, manually remove bad proxies and set "skip proxy checks" to true.

**Comment by JijaProGamer** [comment]
Fixed
