### ISSUE TITLE
Error Sign in to confirm you’re not a bot

### ISSUE THREAD

**Issue by Velix12344** [JijaProGamer/Youtube-Rumble-View-Bot#39]
Server started on http://127.0.0.1:6554
Headless server started successfully
UnrecoverableError: Sign in to confirm you’re not a bot
    at exports.playError (/workspaces/YouTube-view-bot/Youtube-Rumble-View-Bot/node_modules/@distube/ytdl-core/lib/utils.js:164:12)
    at exports.getBasicInfo (/workspaces/YouTube-view-bot/Youtube-Rumble-View-Bot/node_modules/@distube/ytdl-core/lib/info.js:46:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) Promise {
  <rejected> UnrecoverableError: Sign in to confirm you’re not a bot
      at exports.playError (/workspaces/YouTube-view-bot/Youtube-Rumble-View-Bot/node_modules/@distube/ytdl-core/lib/utils.js:164:12)
      at exports.getBasicInfo (/workspaces/YouTube-view-bot/Youtube-Rumble-View-Bot/node_modules/@distube/ytdl-core/lib/info.js:46:25)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
}

**Comment by JijaProGamer** [comment]
That only appears when using bad proxy providers. Not much I can do, just switch to a more trusty proxy provider.
